spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:30010/auth/realms/eureka

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, beans

logging:
  config: classpath:log4j2-debug-spring.xml
  level:
    org.springframework.web.cors.reactive.DefaultCorsProcessor: debug